const manifest = {
  id: "com.tamilott.catalog",
  version: "1.1.0",
  name: "Tamil OTT Catalog",
  description: "Tamil movies, web series, TV shows & short films from Sun NXT, ZEE5, Disney+ Hotstar, Aha Tamil, Amazon MX Player, Kalaignar TV and Sony LIV.",
  logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Tamil_language_logo.svg/200px-Tamil_language_logo.svg.png",
  contactEmail: "kanandhkumar@gmail.com",
  resources: ["catalog", "meta"],
  types: ["movie", "series"],
  idPrefixes: ["tt", "tmdb:"],
  behaviorHints: { adult: false, p2p: false, configurable: false },
  catalogs: [
    { id: "sunnxt_movies", type: "movie", name: "Sun NXT – Tamil Movies",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Comedy","Thriller","Romance","Horror","Family","Devotional"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "sunnxt_series", type: "series", name: "Sun NXT – Tamil TV Shows",
      extra: [{ name: "genre", isRequired: false, options: ["Drama","Comedy","Reality","News","Crime","Family"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "sunnxt_webseries", type: "series", name: "Sun NXT – Tamil Web Series",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Thriller","Crime","Romance"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "sunnxt_shorts", type: "series", name: "Sun NXT – Tamil Short Films & Originals",
      extra: [{ name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "zee5_movies", type: "movie", name: "ZEE5 – Tamil Movies",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Comedy","Thriller","Romance","Horror","Family","Sci-Fi"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "zee5_series", type: "series", name: "ZEE Tamil – TV Shows",
      extra: [{ name: "genre", isRequired: false, options: ["Drama","Comedy","Reality","Crime","Family"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "zee5_webseries", type: "series", name: "ZEE5 – Tamil Web Series & Originals",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Thriller","Crime","Romance"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "zee5_shorts", type: "series", name: "ZEE5 – Tamil Short Films",
      extra: [{ name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "hotstar_movies", type: "movie", name: "Disney+ Hotstar – Tamil Movies",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Comedy","Thriller","Romance","Horror","Family","Sci-Fi","Animation"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "hotstar_series", type: "series", name: "Disney+ Hotstar – Tamil TV Shows",
      extra: [{ name: "genre", isRequired: false, options: ["Drama","Comedy","Reality","Crime","Family"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "hotstar_webseries", type: "series", name: "Disney+ Hotstar – Tamil Web Series & Specials",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Thriller","Crime","Romance","Sci-Fi"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "hotstar_shorts", type: "series", name: "Disney+ Hotstar – Tamil Short Films & Originals",
      extra: [{ name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "aha_movies", type: "movie", name: "Aha Tamil – Movies",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Comedy","Thriller","Romance","Horror","Family"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "aha_webseries", type: "series", name: "Aha Tamil – Web Series & Originals",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Thriller","Crime","Romance","Comedy"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "aha_shorts", type: "series", name: "Aha Tamil – Short Films",
      extra: [{ name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "mxplayer_movies", type: "movie", name: "Amazon MX Player – Tamil Movies",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Comedy","Thriller","Romance","Horror","Family"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "mxplayer_series", type: "series", name: "Amazon MX Player – Tamil TV Shows",
      extra: [{ name: "genre", isRequired: false, options: ["Drama","Comedy","Reality","Crime","Family"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "mxplayer_webseries", type: "series", name: "Amazon MX Player – Tamil Web Series & Originals",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Thriller","Crime","Romance"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "mxplayer_shorts", type: "series", name: "Amazon MX Player – Tamil Short Films",
      extra: [{ name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "kalaignar_movies", type: "movie", name: "Kalaignar TV / K Vision – Tamil Movies",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Comedy","Thriller","Romance","Devotional","Family"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "kalaignar_series", type: "series", name: "Kalaignar TV / K Vision – Tamil TV Shows",
      extra: [{ name: "genre", isRequired: false, options: ["Drama","Comedy","Reality","News","Devotional","Family"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "kalaignar_webseries", type: "series", name: "Kalaignar TV / K Vision – Tamil Web Series",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Thriller","Crime","Romance"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "kalaignar_shorts", type: "series", name: "Kalaignar TV / K Vision – Short Films & Originals",
      extra: [{ name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "sonyliv_movies", type: "movie", name: "Sony LIV – Tamil Movies",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Comedy","Thriller","Romance","Horror","Family","Sci-Fi"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "sonyliv_series", type: "series", name: "Sony LIV – Tamil TV Shows",
      extra: [{ name: "genre", isRequired: false, options: ["Drama","Comedy","Reality","Crime","Family","News"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "sonyliv_webseries", type: "series", name: "Sony LIV – Tamil Web Series & Originals",
      extra: [{ name: "genre", isRequired: false, options: ["Action","Drama","Thriller","Crime","Romance","Comedy"] }, { name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
    { id: "sonyliv_shorts", type: "series", name: "Sony LIV – Tamil Short Films",
      extra: [{ name: "search", isRequired: false }, { name: "skip", isRequired: false }] },
  ],
};

module.exports = manifest;
